name: tomopyui-testing-docs
channels:
  - conda-forge/label/widgetsnbextension_dev
  - conda-forge/label/jupyterlab_widgets_rc
  - conda-forge/label/ipywidgets_dev
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tomopy
  - dxchange
  - jupyterlab
  - astropy
  - ipyfilechooser
  - ipywidgets=8
  - widgetsnbextension
  - jupyterlab_widgets
  - ca-certificates
  - certifi
  - openssl
