name: tomopyui-mpl
channels:
  - conda-forge/label/widgetsnbextension_dev
  - conda-forge/label/jupyterlab_widgets_rc
  - conda-forge/label/ipywidgets_dev
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tomopy
  - ca-certificates
  - openssl
  - dxchange
  - jupyterlab
  - certifi
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets
  - ipyfilechooser
  - astropy
